#!/bin/sh
#
# Upload script for url-title-bot
# Add to crontab 
#  0 * * * * /path/to/upload-html 2>&1

FILE="/path/to/urls.html"
if test `find "$FILE" -cmin -60`
then
    scp -i ~/.ssh/identity $FILE user@host:~/public-html/
fi

